version: '3'
services:
  db:
    image: ankane/pgvector
    restart: "no"
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: thigato
      POSTGRES_PASSWORD: 424242
      POSTGRES_DB: thigato
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
